export default {
	env: 'development',
	db: 'mongodb://localhost:27017/test',
	port: 8080,
	TOKEN_SECRET:'AVERYSECRETIVEINFO',
	GOOGLE_SECRET:'I5_Srx8C2kztJfPo5k7tmsLY',
	GOOGLE_MAP_SECRET:'AIzaSyBPSFzXIPJAUYj_7it0yalu1YZKrJ2WVPA',
	GOOGLE_PLACES_SECRET:'AIzaSyCHB9OV1Ce85zJfCSiqZB1fL1co6y2xK9o',
	GOOGLE_GEOCODING:'AIzaSyBemekNaepB2_YeBtYSjdbnsPW9F9W8c5E',
};
